services:
  postgres:
    image: postgres:16
    container_name: mini-erp-db
    environment:
      POSTGRES_DB: mini_erp
      POSTGRES_USER: erp_user
      POSTGRES_PASSWORD: erp_pass
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: